title: selexin.com
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  For years I've been hacking away on hardware and software projects, and it's about time I started documenting some stuff.
baseurl: ""
url: "https://selexin.com"
show_excerpts: true
# twitter_username: selexin
github_username:  se1exin

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea/

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

disqus:
  shortname: selexin-com
google_analytics: UA-37983866-4

